name: Docker Image CI

on:
  push:
     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: auth
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build docker image
      run: |
        docker build -t angelvarela2412/graphql:0.0.1 .
    - name: Push docker image
      run: |
        docker push angelvarela2412/graphql:0.0.1
        docker push angelvarela2412/graphql:latest
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
